#!/usr/bin/env bash
tmp=$(upower -i $(upower -e | grep 'BAT'))

percentage_full=$(echo $tmp | grep percentage | awk 'match($0, /[0-9]+%/) { print substr($0, RSTART, RLENGTH) }')
percentage=${percentage_full::-1}

text_status=$(echo $tmp | grep -E "state:\s+[a-z-]+" -o | awk '{ print $2 }');

case $text_status in
  'charging')
      icon_status='🔌'
    ;;
  'discharging')
      icon_status='💻'
    ;;
  'fully-charged')
      icon_status='✔️'
    ;;
  *)
      icon_status=$text_status;
    ;;
esac

last_value=$(cat /tmp/battery_last_value)
if [[ $percentage -lt 25 ]] && ! [[ $percentage -eq $last_value ]] && [[ $text_status = 'discharging' ]];
then
  if [[ $percentage -lt 15 ]];
  then
    notify-send -u critical -t 15000 "Low battery" "Battery is critically low: $percentage%"
    play -q /usr/share/sounds/gnome/default/alerts/sonar.ogg
  else
    notify-send -t 3000 "Low battery" "Battery is $percentage%"
  fi
  echo $percentage > /tmp/battery_last_value
fi

echo "🔋$percentage%($icon_status)"
