#!/bin/bash

[[ -z "$1" ]] && NAME=js || NAME="$1"
SANDBOX_NAME="$NAME-sandbox"
FILE="index.$NAME"
FOLDER="$HOME/sandbox/$SANDBOX_NAME"
case $NAME in
  js) 
    COMMAND="nodemon -w $FILE -x \"clear; node $FILE\""
    ;;
  cpp) 
    COMMAND="nodemon -C -w $FILE -x \"clear; g++ $FILE -o index.o; ./index.o\""
    echo "cpp"
    ;;
  *) 
    echo "Unrecognized type: $1"; 
    echo "Available types: js, cpp"
    exit 1;
    ;;
esac

echo $FILE
echo $SANDBOX_NAME
if [ -z $(command -v tmux) ];
then
  echo "No tmux found"
  echo "Please install tmux firstly"
  exit 1;
fi

tmux has-session -t $SANDBOX_NAME
if [ $? != 0 ];
then
  [ ! -d $FOLDER ] && mkdir $FOLDER && cd $FOLDER
  [ ! -f $FILE ] && touch $FILE
  clear
  tmux new-session -s $SANDBOX_NAME -n sandbox -d
  tmux send-keys -t $SANDBOX_NAME "clear" C-m
  tmux send-keys -t $SANDBOX_NAME "$COMMAND" C-m
  tmux split-window -h -t $SANDBOX_NAME
  tmux send-keys -t $SANDBOX_NAME "sleep 0.5 && nvim $FILE" C-m
fi
tmux attach -t $SANDBOX_NAME
