name: sandbox-c
root: ~/sandboxes/sandbox-c

startup_pane: 2

windows:
  - editor:
      pre:
        - touch main.c
      layout: even-horizontal
      panes:
        - make c --makefile=../Makefile
        - sleep 0.5 && nvim main.c
