name: sandbox-cpp
root: ~/sandboxes/sandbox-cpp

startup_pane: 2

windows:
  - editor:
      pre:
        - touch main.cpp
      layout: even-horizontal
      panes:
        - make cpp --makefile=../Makefile
        - sleep 0.5 && nvim main.cpp
