name: sandbox-js-4
root: ~/sandboxes/sandbox-js-4

startup_pane: 2

windows:
  - editor:
      pre:
        - touch index.js
      layout: even-horizontal
      panes:
        - npm start
        - sleep 0.5 && nvim index.js
