name: sandbox-parcel5
root: ~/sandboxes/sandbox-parcel5

startup_window: 2

windows:
  - building:
      panes:
        - npm start
  - editor:
      pre:
        - touch index.html
        - touch main.js
      panes:
        - sleep 0.5 && nvim main.js
