# ~/.tmuxinator/saas-authn-ui.yml

name: saas-authn-ui
root: ~/projects/saas-authn-ui

windows:
  - runs:
      layout: even-horizontal
      panes:
        - npm run start
        - npm run start-mock-server
  - work:
