# /home/vtymoshchyk/.config/tmuxinator/sandbox-sed.yml

name: sandbox-terminal
root: ~/sandboxes/sandbox-terminal

startup_pane: 2

windows:
  - editor:
      panes:
        - sleep 0.5 && nvim commands.bash
  - nodemon:
      layout: even-vertical
      panes:
        - npm start
        - alacritty --command ./initializing &
