# /home/vtymoshchyk/.config/tmuxinator/wj.yml

name: wj
root: ~/wj/workjam-web/

startup_window: compiling
startup_pane: 2
windows:
  - compiling:
      pre:
        - sleep 0.5 && clear
      layout: even-horizontal
      panes:
        - npm run start
        -
  - panes:
      panes:
        - 
      
