#!/bin/bash

cd ~/Downloads

wget "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"

sudo chmod u+x ./kubectl

sudo mv ./kubectl /usr/local/bin/
