#!/bin/bash

package="slack-desktop-4.4.3-amd64.deb"
folder="~/Downloads"

[[ ! -d $folder ]] && mkdir $folder
cd $foldler 
sudo wget "https://downloads.slack-edge.com/linux_releases/${package}"
sudo apt install -y "./$package"
