lua:
	nodemon -e lua -x "clear && lua main.lua || exit 1"
c:
	nodemon -e c -x "clear && cc main.c -o _executable && ./_executable"
cpp:
	nodemon -e cpp -x "clear && g++ main.cpp -o _executable && ./_executable"
bash:
	nodemon -e bash -x "clear && bash main.bash || exit 1"
go:
	nodemon -e go -x "clear && go run main.go || exit 1"
