lua:
	nodemon -e lua -x "clear && lua main.lua || exit 1"
c:
	nodemon -e c,h -x "clear && gcc *.c -o _executable && ./_executable"
cpp:
	nodemon -e cpp -x "clear && g++ main.cpp -o _executable && ./_executable"
bash:
	nodemon -e bash -x "clear && bash main.bash || exit 1"
go:
	nodemon -e go -x "clear && go run main.go || exit 1"
js:
	nodemon -e js -x "clear && node main.js || exit 1"
java:
	nodemon -e java -x "clear && javac *.java && java Main || exit 1"
